apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saffaran-api-hpa
  namespace: saffaran
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saffaran-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
