name: Deploy to AWS Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: terraform
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Build & Push Docker Image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your_account_id>.dkr.ecr.us-east-1.amazonaws.com
          docker build -t saffaran-api ./app
          docker tag saffaran-api:latest <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/saffaran-api:latest
          docker push <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/saffaran-api:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name saffaran-eks-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml
